id: opecha:P000458
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ2398
  title: གུང་ཐང་པའི་ཤེས་རབ་སྙིང་པོའི་སྔགས་ཀྱི་རྣམ་བཤད་དང་ཅོ་ནེ་བླ་མ་བློ་བཟང་རྒྱ་མཚོའི་ལྟ་མགུར་སོགས
  volume: ''
  author: ''
