id: P000458
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-16 15:41:00.129527
source_metadata:
  id: bdr:W1CZ2398
  title: གུང་ཐང་པའི་ཤེས་རབ་སྙིང་པོའི་སྔགས་ཀྱི་རྣམ་བཤད་དང་ཅོ་ནེ་བླ་མ་བློ་བཟང་རྒྱ་མཚོའི་ལྟ་མགུར་སོགས
  author: ''
  volumes:
    eb3ee1891bb24fc2bdc7854592ef2f6e:
      image_group_id: I1CZ2452
      title: Volume 1 of gung thang pa'i shes rab snying po'i sngags kyi rnam bshad
        dang co ne bla ma blo bzang rgya'i mtsho'i lta mgur sogs
      volume_number: 1
      total_pages: 242
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
